development:
  adapter: postgresql
  encoding: unicode
  database: rsvp_development
  pool: 5

test:
    adapter: postgresql
    encoding: unicode
    database: rsvp_test
    pool: 5

production:
    adapter: postgresql
    encoding: unicode
    database: rsvp_production
    pool: 5
